server:
  port: 9001

spring:
  application:
    name: demo

  datasource:
    platform: mysql
    url: jdbc:mysql://database-1.cb2jmajikv2k.ap-northeast-2.rds.amazonaws.com/prod_careeix?autoReconnect=true # dev
    username: admin
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver # mysql 8버전